title: boomj
email: manfred@simpligility.com
description: >- # this means to ignore newlines until "baseurl:"
  A template static site setup using `Boo`tstrap, `M`aterial Design, and `J`ekyll for starters.
baseurl: "boomj"
url: "https://simpligility.github.io/"

# Build settings
theme: minima
plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/f
  - vendor/gems/
  - vendor/ruby/
  - README.md
